name: Deploy backend
on: workflow_call
jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
        - name: Build backend
          run: echo "Building backend build (Run Unit tests), generate and create docker image"
    deploy-stage:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Deploy backend to stage/review app
          run: echo "Deploy backend to stage/review app"