name: Deploy to production
on: workflow_call
jobs:
    deploy-backend: 
        runs-on: ubuntu-latest
        steps:
        - name: Deploy backend to prod
          run: echo "Deploy backend to prod"

    deploy-frontend:
        runs-on: ubuntu-latest
        steps:
        - name: Deploy frontend to prod
          run: echo "Deploy frontend to prod"