name: Deploy frontend
on: workflow_call
jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
        - name: Build frontend
          run: echo "Building frontend build (Run Unit tests, run linters), generate and create docker image"
    deploy-stage:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Deploy frontend to stage/review app
          run: echo "Deploy frontend to stage/review app"