name: TeamCity deployment

on:
    push:
    workflow_dispatch:

jobs:
    # Build backend and deploy on staging/review app
    backend:
        uses: ./.github/workflows/backend-stage.yml        
    # Build frontend and deploy on staging/review app
    frontend:
        uses: ./.github/workflows/frontend-stage.yml

    # Run API autotests
    automation-api:
        needs: [backend, frontend]
        uses: ./.github/workflows/automation.yml
        with:
            tests_folder: Api

    # Run UI autotests
    automation-ui:
        needs: [backend, frontend]
        uses: ./.github/workflows/automation.yml
        with:
            tests_folder: UI
    
    manual-prod-approval:
        needs: [automation-api, automation-ui]
        runs-on: ubuntu-latest
        environment: 'prod'
        steps:
            - name: Approve backend and frontent production
              run: echo Approved to production

    deploy-prod:
        needs: manual-prod-approval
        uses: ./.github/workflows/deploy-prod.yml

    